[project]
name = "agent-clever-hans"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11,<3.14"
dependencies = [
    "db-dtypes>=1.5.0",
    "dotenv>=0.9.9",
    "duckdb>=1.4.3",
    "einops>=0.8.0",
    "fastapi>=0.128.0",
    "fire>=0.7.1",
    "google>=3.0.0",
    "google-api-python-client>=2.187.0",
    "google-cloud>=0.34.0",
    "google-cloud-bigquery>=3.39.0",
    "google-cloud-bigquery-storage>=2.36.0",
    "google-cloud-storage>=3.7.0",
    "h5py>=3.15.1",
    "matplotlib>=3.10.8",
    "numpy==1.26.4",
    "openbabel-wheel==3.1.1.22",
    "pandas>=2.3.3",
    "pyarrow>=22.0.0",
    "pybel>=0.15.5",
    "pytdc>=0.4.1",
    "scikit-learn==1.1.3",
    "rdkit>=2025.9.3",
    "tqdm>=4.67.1",
    "transformers>=4.57.3",
    "uvicorn>=0.40.0",
    "wandb==0.18.7",
    "setuptools>=80.0.0",
    "langchain==1.0.1",
    "langchain-anthropic",
    "langchain-openai",
    "langgraph",
    "langchain-google-genai",
    "langchain-deepseek",
    "langchain-community>=0.4.1",
]

[dependency-groups]
dev = [
    "ipykernel>=7.1.0",
]

[tool.uv]
override-dependencies = [
    "numpy==1.26.4",
    "scikit-learn==1.1.3",
]
